### ISSUE TITLE
[Feature] : Update the mail service for the Contactus page 

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot from 2024-07-13 07-07-42](https://github.com/user-attachments/assets/bbfe312d-b76b-462b-9659-c8e14e29f859)

- In this `/Contact` page cannot responding the mail if there backend url missing and allowing for the backend.

### Use Case

- simply change to the backend Url it's working for normally.
- please assign me.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, you can check out https://github.com/CodeHarborHub/codeharborhub.github.io/pull/3012. The issue seems to be originating from the API rendered by Render. I have deployed my backend using Render, and it appears that the response times are slower, possibly due to delays or waiting periods.

**Comment by Ajay-Dhangar** [comment]
![image](https://github.com/user-attachments/assets/fc69d178-af48-4ab2-af0a-21e1360c7ab2)

Wait, I want to deploy it on another platform and then check if it's working fine or not.

**Comment by sivaprasath2004** [comment]
@Ajay-Dhangar yes onrender can be slow of the deploy it's make some time to response use another platform to deploy
