### ISSUE TITLE
[Feature Request]: Leetcode Solution 51-60

### ISSUE THREAD

**Issue by mehtakevan** [CodeHarborHub/codeharborhub.github.io#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add leetcode solution 51-60

### Use Case

1. It will have proper description and comments
2. I will give solution in 2 programming language

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor

**Comment by mehtakevan** [comment]
@Ajay-Dhangar Can you please assign this issue to me.

**Comment by Ajay-Dhangar** [comment]
Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. And [live preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum)

I am assigning you a level 3 because I need high-quality content similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1). This assignment isn't just for one file but will be based on the quality of your content overall. If your content is good and valuable, I will also assign level 3 to your pull requests. Otherwise, I will assign level 2. I am assigning this issue level 3 because I need more valuable content.

**Comment by Ajay-Dhangar** [comment]
@mehtakevan can you complete your task otherwise I will close it.
