### ISSUE TITLE
[Geeks for Geeks Solution]: Swap kth elements

### ISSUE THREAD

**Issue by iamanolive** [CodeHarborHub/codeharborhub.github.io#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Swap kth elements (https://www.geeksforgeeks.org/problems/swap-kth-elements5500/1?page=1&difficulty=School&sortBy=difficulty)

### Use Case

solution implementation and explanation

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. And [live preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum)

I am assigning you a level 3 because I need high-quality content similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1). This assignment isn't just for one file but will be based on the quality of your content overall. If your content is good and valuable, I will also assign level 3 to your pull requests. Otherwise, I will assign level 2. I am assigning this issue level 3 because I need more valuable content.

**Comment by Ajay-Dhangar** [comment]
@iamanolive Please complete your task otherwise I will close it.
