### ISSUE TITLE
[Feature Request]:  Add Solution to LC Problem - 2032

### ISSUE THREAD

**Issue by sreevidya-16** [CodeHarborHub/codeharborhub.github.io#3480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Problem Name - [Two Out of Three](https://leetcode.com/problems/two-out-of-three/)

I need to add solution to this Problem with detailed explanation

### Use Case

[Two Out of Three](https://leetcode.com/problems/two-out-of-three/)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Hi @sreevidya-16,

Here are some [Guidelines for Writing DSA Problem Solutions](https://github.com/orgs/CodeHarborHub/discussions/3369) for your reference. Please ensure that all your contents follow these guidelines so that we can maintain the quality of the solutions at a high level.

Feel free to ask if you have any questions.
