### ISSUE TITLE
[Bug]: Quiz Section Deployment Issue on CodeHarborHub.

### ISSUE THREAD

**Issue by SCR01** [CodeHarborHub/codeharborhub.github.io#3632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm experiencing a deployment issue on CodeHarborHub. When trying to deploy my app on Vercel, I receive a 404: NOT_FOUND error with the code DEPLOYMENT_NOT_FOUND.

Upon attempting to access my deployed app, the browser shows a 404: NOT_FOUND error message indicating that the deployment cannot be found.

### Expected behavior

I expected the app to be successfully deployed and accessible via the provided URL.

### Add ScreenShots

![Screenshot 2024-07-20 124107](https://github.com/user-attachments/assets/83fb201a-90d4-473b-90f4-54082a428b99)

Bug Video:

https://github.com/user-attachments/assets/12cc2846-1c27-46d8-96fd-8353207a9e0f

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@SCR01 I know this is for a quiz app, but since that isn't a part of our site, you can't debug it here. You can still create a page or component for it if you like. The best way to do that would be with reusable components where you can pass props. That would work well for tech quizzes on HTML, CSS, JS, React, etc.

**Comment by SCR01** [comment]
@Ajay-Dhangar Ok, then I will work on this issue separately.
