### ISSUE TITLE
[Feature]: Add `Swift` language in `Course ` section 

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- Swift is a powerful and intuitive programming language for all Apple platforms. It’s easy to get started using Swift, with a concise-yet-expressive syntax and modern features you’ll love. Swift code is safe by design and produces software that runs lightning‑fast.

-please assign me..

### Beginner Level

**1. Introduction to Swift** 

**2. Basic Syntax and Structure** 

**3. Control Flow** 

**4. Functions** 

**5. Collections** 

**6. Strings** 

**7. Optionals** 

### Intermediate Level

**1. Advanced OOP Concepts** 

**2. Enumerations and Optionals** 

**3. Protocols and Extensions** 

**4. Closures** 

**5. Error Handling** 

**6. Generics** 

**7. Memory Management** 

**8. Working with JSON and APIs** 

### Advanced Level

**1. Advanced Protocols and Extensions** 

**2. Advanced Generics** 

**3. Concurrency and Multithreading** 

**4. SwiftUI** 

**5. Networking and Web Services** 

**6. Core Data** 

**7. Performance Optimization** 
 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar please assign me..

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, I'm on this, but I'm going to need some time. The codebase for this project is huge, so I need to optimize everything before I can start adding the course content. I don't want to introduce any errors or issues due to the sheer size of the project.

I have all the topics and content figured out, so once the code is optimized and running smoothly, it shouldn't take too long to add the course directory. Here is the error I'm getting:

```bash
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

I'll keep you updated on my progress.
