### ISSUE TITLE
[Feature]: Add `Go` language course

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- If i want to add the `Go` lanugage.
- please assign me.

### Use Case

**Go Language Overview**: Go is an open-source programming language created by Google in 2007 and released to the public in 2009. It was designed by Robert Griesemer, Rob Pike, and Ken Thompson and aims to be simple, efficient, and reliable. Go is statically typed and has a syntax that is similar to C, but it also includes features from other languages like Python and JavaScript. It's known for its strong support for concurrent programming and its garbage collection capabilities.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar ,could you please assign me..

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, I'm on this, but I'm going to need some time. The codebase for this project is huge, so I need to optimize everything before I can start adding the course content. I don't want to introduce any errors or issues due to the sheer size of the project.

I have all the topics and content figured out, so once the code is optimized and running smoothly, it shouldn't take too long to add the course directory. Here is the error I'm getting:

```bash
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

I'll keep you updated on my progress.
