### ISSUE TITLE
[Tutorials ]: add Tutorials on Database Management System ( DBMS ) 

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to tutorials on DBMS and _some docs_ under that tutorial.

### Use Case

use can know more about DBMS

### Benefits

use can know more about DBMS

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , please assign this issue to me.

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

So, wait for some time.
